const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AdvancedRandom,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Button,
		C3.Plugins.Json,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Behaviors.destroy,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Flash,
		C3.Plugins.TextBox,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Behaviors.Timer,
		C3.Plugins.TiledBg,
		C3.Behaviors.Physics,
		C3.Plugins.video,
		C3.Plugins.HTMLElement,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Rotate,
		C3.Plugins.GameAnalytics,
		C3.Plugins.NinePatch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.GameAnalytics.Acts.addDesignEvent,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTable,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.AdvancedRandom.Acts.AddProbabilityEntry,
		C3.Plugins.AdvancedRandom.Exps.Weighted,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.AdvancedRandom.Acts.RemoveProbabilityEntry,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.GameAnalytics.Acts.addResourceEvent,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Acts.SetMovingAngle,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Behaviors.MoveTo.Acts.SetDeceleration,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Acts.SetEffectEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Plugins.Text.Cnds.CompareY,
		C3.Plugins.Text.Cnds.PickDistance,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.HTMLElement.Acts.SetContent,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.HTMLElement.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Browser.Exps.ExecJS,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Exps.Get,
		C3.JavaScriptInEvents.General_Event18_Act22,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.LoadObjectTexturesByName,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.GameAnalytics.Acts.configureBuild,
		C3.Plugins.GameAnalytics.Acts.addAvailableResourceItemType,
		C3.Plugins.GameAnalytics.Acts.addAvailableResourceCurrency,
		C3.Plugins.GameAnalytics.Acts.initialize,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.NinePatch.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{AdvancedRandom: 0},
	{AJAX: 0},
	{Audio: 0},
	{Browser: 0},
	{Button: 0},
	{JSON: 0},
	{Legend_Array: 0},
	{Norm_Array: 0},
	{Rare_Array: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Battle_Array: 0},
	{Door_Array: 0},
	{EventsLeft_Array: 0},
	{NormRandom: 0},
	{RareRandom: 0},
	{LegendRandom: 0},
	{Mission_Array: 0},
	{BaseBackground: 0},
	{Battle_BG: 0},
	{Bullet: 0},
	{Battle_icon: 0},
	{block: 0},
	{box1: 0},
	{Button_continue: 0},
	{Button_continue2: 0},
	{Cooper: 0},
	{Cooper_inv: 0},
	{Copper_count: 0},
	{DestroyOutsideLayout: 0},
	{Tween: 0},
	{crack: 0},
	{DataSendText: 0},
	{Debug: 0},
	{debug_button: 0},
	{debug_deep: 0},
	{DecodedName: 0},
	{Вууз: 0},
	{Deep_txt: 0},
	{Type: 0},
	{Fade: 0},
	{MoveTo: 0},
	{Flash: 0},
	{Enemy1: 0},
	{EnterName: 0},
	{EnterScore: 0},
	{Event_line: 0},
	{Event_stat_txt: 0},
	{Event_txt: 0},
	{EventButton1: 0},
	{EventButton2: 0},
	{Final_score: 0},
	{Sine: 0},
	{Final_Score2: 0},
	{FinalButton: 0},
	{food_btn: 0},
	{Fox: 0},
	{Frame: 0},
	{Gold: 0},
	{Gold_count: 0},
	{Gold_inv: 0},
	{ground1: 0},
	{ground2: 0},
	{ground_rocks1: 0},
	{ground_rocks2: 0},
	{EnergyFrame: 0},
	{Group4: 0},
	{Happiness_baff_count: 0},
	{Happiness_baff_txt: 0},
	{Happiness_button: 0},
	{header: 0},
	{Help_button: 0},
	{Help_close: 0},
	{Help_panel: 0},
	{Hunger_baff_count: 0},
	{Hunger_baff_txt: 0},
	{Hunger_button: 0},
	{icon: 0},
	{RecordID: 0},
	{Pin: 0},
	{Inv_close: 0},
	{Inventory: 0},
	{Inventory_frame: 0},
	{Iron: 0},
	{Iron_count: 0},
	{Iron_inv: 0},
	{NormTest: 0},
	{Timer: 0},
	{junk: 0},
	{junk2: 0},
	{Lead: 0},
	{Lead_count: 0},
	{Lead_inv: 0},
	{load32_: 0},
	{mark: 0},
	{mark2: 0},
	{mask: 0},
	{mask2: 0},
	{Middle_frame: 0},
	{money_bar: 0},
	{Monster_Power: 0},
	{Music: 0},
	{Name: 0},
	{Pickaxe_Power: 0},
	{progress_bar_fill: 0},
	{Progress_bar_frame: 0},
	{progress_bar_milestones1: 0},
	{Resource_frame: 0},
	{result_window: 0},
	{rocks_tunnel_: 0},
	{Shadow: 0},
	{Silver: 0},
	{Silver_count: 0},
	{Silver_inv: 0},
	{Small_frame: 0},
	{Sound: 0},
	{Sprite2: 0},
	{take_reward_button: 0},
	{TextRandom: 0},
	{version: 0},
	{TiledBackground: 0},
	{tool: 0},
	{tunnel1: 0},
	{tunnel2: 0},
	{hearth_txt: 0},
	{health_sprite: 0},
	{health_sprite2: 0},
	{health_sprite3: 0},
	{PickAxe_Range_txt: 0},
	{mood_txt: 0},
	{Happiness_sprite: 0},
	{Happiness_Sprite2: 0},
	{Happiness_Sprite3: 0},
	{hunger_txt: 0},
	{Hunger_Sprite: 0},
	{Hunger_Sprite2: 0},
	{Hunger_Sprite3: 0},
	{purity_txt: 0},
	{Purity_Sprite: 0},
	{Purity_Sprite2: 0},
	{Purity_Sprite3: 0},
	{dontxt: 0},
	{sleep_debug: 0},
	{AnimType: 0},
	{junktest: 0},
	{obj_health_icon: 0},
	{obj_mood_icon: 0},
	{obj_hunger_icon: 0},
	{obj_purity_icon: 0},
	{LocalName: 0},
	{Tg_ID: 0},
	{api_debug: 0},
	{RareTest: 0},
	{LegendTest: 0},
	{CurrentEventTxt: 0},
	{tap_object_txt: 0},
	{ProbabStatEventTxt: 0},
	{Attack_boom: 0},
	{Baff_effect: 0},
	{Pickaxedisplay_txt: 0},
	{progress_bar_milestones2: 0},
	{progress_bar_milestones4: 0},
	{progress_bar_milestones3: 0},
	{aid_btn: 0},
	{button_frame: 0},
	{Down_panel: 0},
	{energy_progress_bar: 0},
	{settings_btn: 0},
	{workshop_btn: 0},
	{shower_btn: 0},
	{sleep_btn: 0},
	{mood_progress_bar_green: 0},
	{stats_panel: 0},
	{tool_btn: 0},
	{purity_progress_bar_green: 0},
	{health_progress_bar_green: 0},
	{hunger_progress_green: 0},
	{NoMoney_panel: 0},
	{main_shadow: 0},
	{money_count_txt: 0},
	{music_box: 0},
	{music_Check: 0},
	{no_btn_lvlup: 0},
	{no_btn_sleep: 0},
	{no_btn_upgrade: 0},
	{no_btn_workshop: 0},
	{NoMoneyTxt: 0},
	{options_panel: 0},
	{Player_name_txt: 0},
	{PlayerShadow: 0},
	{purity_stat_txt: 0},
	{revive_button: 0},
	{shop_shadow: 0},
	{shop_window: 0},
	{sleep_panel: 0},
	{SleepTxt: 0},
	{Small_obj_1: 0},
	{sound_box: 0},
	{sound_Check: 0},
	{Sound_txt: 0},
	{Physics: 0},
	{Sprite: 0},
	{Sprite4: 0},
	{Stat_count: 0},
	{taken_money_txt: 0},
	{Tap_obj: 0},
	{upgrade_btn: 0},
	{Upgrade_price_txt: 0},
	{workshop_bags_buy_btn: 0},
	{workshop_bags_buy_check: 0},
	{workshop_bags_price_txt: 0},
	{workshop_bags_txt: 0},
	{workshop_buy_panel: 0},
	{workshop_buy_txt: 0},
	{workshop_deep_buy_btn: 0},
	{workshop_deep_txt: 0},
	{workshop_header_txt: 0},
	{workshop_main_panel: 0},
	{workshop_pickaxe_buy_check: 0},
	{workshop_pickaxe_price_txt: 0},
	{workshop_Pickaxe_skin_txt: 0},
	{workshop_pickxe_buy_btn: 0},
	{workshop_shadow: 0},
	{workshop_upgrade_price_txt: 0},
	{yes_btn_lvlup: 0},
	{yes_btn_sleep: 0},
	{yes_btn_buy: 0},
	{yes_btn_workshop: 0},
	{"1_item_1added_stat_txt": 0},
	{"1_item_2added_stat_txt": 0},
	{"1_item_price_txt": 0},
	{"1_item_stat_bonus_icon": 0},
	{"1_slot_item": 0},
	{"1_slot_item_count": 0},
	{slot_buy_btn: 0},
	{"2_item_1added_stat_txt": 0},
	{"2_item_2added_stat_txt": 0},
	{"2_slot_item": 0},
	{"2_slot_item_count": 0},
	{"3_item_1added_stat_txt": 0},
	{"3_item_2added_stat_txt": 0},
	{"3_slot_item": 0},
	{"3_slot_item_count": 0},
	{"4_slot_item": 0},
	{"4_slot_item_count": 0},
	{"5_slot_item": 0},
	{"5_slot_item_count": 0},
	{"6_slot_item": 0},
	{"6_slot_item_count": 0},
	{added_stat_txt1: 0},
	{added_stat_txt2: 0},
	{close_workshop: 0},
	{debug_energy_btn: 0},
	{debug_energy_btn_2: 0},
	{debug_health_btn: 0},
	{debug_health_btn2: 0},
	{dont: 0},
	{energy_count_txt: 0},
	{energy_icon: 0},
	{Explosion: 0},
	{hapiness_stat_txt: 0},
	{health_stat_txt: 0},
	{hunger_stat_txt: 0},
	{levelup_panel: 0},
	{LvlupTxt: 0},
	{"2_item_price_txt": 0},
	{"3_item_price_txt": 0},
	{mood_progress_bar_yellow: 0},
	{mood_progress_bar_red: 0},
	{purity_progress_yellow: 0},
	{purity_progress_red: 0},
	{health_progress_bar_yellow: 0},
	{health_progress_red: 0},
	{hunger_progress_yellow: 0},
	{hunger_progress_red: 0},
	{obj_health_icon_base: 0},
	{obj_hunger_icon_base: 0},
	{obj_mood_icon_base: 0},
	{obj_purity_icon_base: 0},
	{BlockScreen: 0},
	{dino: 0},
	{door_button: 0},
	{doors: 0},
	{DoorTxt: 0},
	{upgrade_price_icon: 0},
	{tutorail_shadow: 0},
	{FoxNews: 0},
	{pulsetime: 0},
	{Cutscene_txt: 0},
	{skip: 0},
	{TutorialHand: 0},
	{TutorialPopup: 0},
	{TutorialMask1: 0},
	{TutorialMask2: 0},
	{TutorialTxt: 0},
	{skip2: 0},
	{debugTxt: 0},
	{debugTxt2: 0},
	{playBtn: 0},
	{DragDrop: 0},
	{NewFox: 0},
	{Rotate: 0},
	{redbull: 0},
	{Loading_animation: 0},
	{Text: 0},
	{GameAnalytics: 0},
	{HitExplosion1: 0},
	{HitExplosion2: 0},
	{"9patch": 0},
	{LoadingBg: 0},
	{loading_txt: 0},
	{Debug_Load_txt: 0},
	{LevelTxt: 0},
	{MultiplierPic: 0},
	{Multiplyer_txt: 0},
	{RecipeIcon: 0},
	{MisiionFrame: 0},
	{MissonIcon: 0},
	{MissionObject: 0},
	{MissionTxt: 0},
	{tunnel: 0},
	{rocks: 0},
	{JunkFam: 0},
	{Event_fam: 0},
	{Digging: 0},
	{Event_stats: 0},
	{Stat_txt: 0},
	{EventUI: 0},
	{Inventory_window: 0},
	{Inventory_count_text: 0},
	{Main_UI_buttons: 0},
	{ProgressBar: 0},
	{Shop_Window_Family: 0},
	{Shop_window_txt_fam: 0},
	{Slot_items: 0},
	{Base_buttons: 0},
	{Sleep_icons: 0},
	{Sound_icons: 0},
	{workshop_main_icons: 0},
	{workshop_buy_btns: 0},
	{workshop_txt: 0},
	{TapIcons: 0},
	{Price_txt: 0},
	{Base_icons: 0},
	{Additional_UI: 0},
	{TutorialImages: 0},
	{AnimCount: 0},
	{JunkAnimCount1: 0},
	{JunkAnimCount2: 0},
	{ItemAnimCount: 0},
	{Deep: 0},
	{Chance: 0},
	{pause: 0},
	{EventStat: 0},
	{Purity: 0},
	{Hunger: 0},
	{Happiness: 0},
	{Health: 0},
	{Choice: 0},
	{ChoiceButton: 0},
	{BattleButton: 0},
	{InvButton: 0},
	{DiggingTutorial: 0},
	{BaseTutorial: 0},
	{Reward1Y: 0},
	{Reward2Y: 0},
	{PickaxePower: 0},
	{EnemyPower: 0},
	{BattleReward: 0},
	{Touched: 0},
	{Happin_baff_count: 0},
	{EventPush: 0},
	{WinBattle: 0},
	{Copper: 0},
	{Score: 0},
	{InventoryON: 0},
	{GameOver: 0},
	{name: 0},
	{AttackLanding: 0},
	{ID: 0},
	{HelpWindow: 0},
	{targetProgress: 0},
	{progressSpeed: 0},
	{maxDepth: 0},
	{junkGO: 0},
	{TapObject: 0},
	{tempHappinessBaffi: 0},
	{tempHungerBaffi: 0},
	{EventCounter: 0},
	{EventType: 0},
	{EventID: 0},
	{EventNormIndex: 0},
	{EventRareIndex: 0},
	{EventLegendIndex: 0},
	{NormX: 0},
	{NormCount: 0},
	{RareX: 0},
	{RareCount: 0},
	{LegendX: 0},
	{LegendCount: 0},
	{NormDone: 0},
	{RareDone: 0},
	{LegendDone: 0},
	{EventStart: 0},
	{Tutorial: 0},
	{TutorialStep: 0},
	{TutorialPause: 0},
	{JunkTutor1: 0},
	{JunkTutor2: 0},
	{InventoryTutorial: 0},
	{InventoryAvailable: 0},
	{BaffTutorTap: 0},
	{TotalResources: 0},
	{BaffTutor: 0},
	{EnemyType: 0},
	{LevelMultiplier: 0},
	{CurrentMission: 0},
	{MissionRecieved: 0},
	{Recipe: 0},
	{ObjSide: 0},
	{Reward1: 0},
	{Reward2: 0},
	{Reward3: 0},
	{EnemyHPmax: 0},
	{EnemyHP: 0},
	{shop_window_tap: 0},
	{"1_item_price": 0},
	{"2_item_price": 0},
	{"3_item_price": 0},
	{"1_item_count": 0},
	{"2_item_count": 0},
	{"3_item_count": 0},
	{"4_item_count": 0},
	{"5_item_count": 0},
	{"6_item_count": 0},
	{Current_money: 0},
	{Upgrade_price: 0},
	{Basket_money: 0},
	{"1_Added_stat": 0},
	{"2_Added_stat": 0},
	{Energy: 0},
	{maxEnergy: 0},
	{"1_item_1_stat": 0},
	{"1_item_2_stat": 0},
	{"2_item_1_stat": 0},
	{"2_item_2_stat": 0},
	{"3_item_1_stat": 0},
	{"3_item_2_stat": 0},
	{NoMoneyWarning: 0},
	{AnimEnd: 0},
	{Purchase: 0},
	{tempHealthValue: 0},
	{tempPurityValue: 0},
	{tempHungerValue: 0},
	{ActionAnim: 0},
	{sleep_window: 0},
	{Sleep: 0},
	{Settings: 0},
	{Workshop: 0},
	{WorkshopUpgradeWindow: 0},
	{workshop_pickaxe_price: 0},
	{workshop_bags_price: 0},
	{WorkshopUpgradePrice: 0},
	{WorkshopUpgradeType: 0},
	{Pickaxe_level: 0},
	{Bags_level: 0},
	{LvlUpgrade: 0},
	{jsonBody: 0},
	{music: 0},
	{sound: 0},
	{death: 0},
	{NoPatience: 0},
	{Start: 0},
	{api: 0},
	{BlockClose: 0},
	{AidShopLvl: 0},
	{WashShopLvl: 0},
	{FoodShopLvl: 0},
	{WarningTXT: 0},
	{BaseTutorialStep: 0},
	{OpenedDoor: 0},
	{WashShopTutor: 0},
	{HealShopTutor: 0},
	{FoodShopTutor: 0},
	{SleepTutor: 0},
	{CanBuyTutor: 0},
	{FullBlock: 0},
	{RedBull: 0},
	{ActiveMainUI: 0},
	{ActiveAdditionalUI: 0},
	{DevMode: 0},
	{Level: 0},
	{SubLevel: 0},
	{cutscene: 0},
	{AirtableLoaded: 0},
	{ImagesLoaded: 0},
	{CombinedProgress: 0}
];

self.InstanceType = {
	AdvancedRandom: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Button: class extends self.IButtonInstance {},
	JSON: class extends self.IJSONInstance {},
	Legend_Array: class extends self.IArrayInstance {},
	Norm_Array: class extends self.IArrayInstance {},
	Rare_Array: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Battle_Array: class extends self.IArrayInstance {},
	Door_Array: class extends self.IArrayInstance {},
	EventsLeft_Array: class extends self.IArrayInstance {},
	NormRandom: class extends self.IArrayInstance {},
	RareRandom: class extends self.IArrayInstance {},
	LegendRandom: class extends self.IArrayInstance {},
	Mission_Array: class extends self.IArrayInstance {},
	BaseBackground: class extends self.ISpriteInstance {},
	Battle_BG: class extends self.ISpriteInstance {},
	Battle_icon: class extends self.ISpriteInstance {},
	block: class extends self.ISpriteInstance {},
	box1: class extends self.ISpriteInstance {},
	Button_continue: class extends self.ITextInstance {},
	Button_continue2: class extends self.ITextInstance {},
	Cooper: class extends self.ISpriteInstance {},
	Cooper_inv: class extends self.ISpriteInstance {},
	Copper_count: class extends self.ITextInstance {},
	crack: class extends self.ISpriteInstance {},
	DataSendText: class extends self.ITextInstance {},
	Debug: class extends self.ITextInstance {},
	debug_button: class extends self.ISpriteInstance {},
	debug_deep: class extends self.ISpriteInstance {},
	DecodedName: class extends self.ITextInstance {},
	Deep_txt: class extends self.ITextInstance {},
	Enemy1: class extends self.ISpriteInstance {},
	EnterName: class extends self.ITextInputInstance {},
	EnterScore: class extends self.ITextInputInstance {},
	Event_line: class extends self.ISpriteInstance {},
	Event_stat_txt: class extends self.ITextInstance {},
	Event_txt: class extends self.ITextInstance {},
	EventButton1: class extends self.ISpriteInstance {},
	EventButton2: class extends self.ISpriteInstance {},
	Final_score: class extends self.ITextInstance {},
	Final_Score2: class extends self.ITextInstance {},
	FinalButton: class extends self.ITextInstance {},
	food_btn: class extends self.ISpriteInstance {},
	Fox: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	Gold: class extends self.ISpriteInstance {},
	Gold_count: class extends self.ITextInstance {},
	Gold_inv: class extends self.ISpriteInstance {},
	ground1: class extends self.ISpriteInstance {},
	ground2: class extends self.ISpriteInstance {},
	ground_rocks1: class extends self.ISpriteInstance {},
	ground_rocks2: class extends self.ISpriteInstance {},
	EnergyFrame: class extends self.ISpriteInstance {},
	Group4: class extends self.ISpriteInstance {},
	Happiness_baff_count: class extends self.ITextInstance {},
	Happiness_baff_txt: class extends self.ITextInstance {},
	Happiness_button: class extends self.ISpriteInstance {},
	header: class extends self.ISpriteInstance {},
	Help_button: class extends self.ISpriteInstance {},
	Help_close: class extends self.ISpriteInstance {},
	Help_panel: class extends self.ISpriteInstance {},
	Hunger_baff_count: class extends self.ITextInstance {},
	Hunger_baff_txt: class extends self.ITextInstance {},
	Hunger_button: class extends self.ISpriteInstance {},
	icon: class extends self.ISpriteInstance {},
	RecordID: class extends self.ITextInstance {},
	Inv_close: class extends self.ISpriteInstance {},
	Inventory: class extends self.ISpriteInstance {},
	Inventory_frame: class extends self.ISpriteInstance {},
	Iron: class extends self.ISpriteInstance {},
	Iron_count: class extends self.ITextInstance {},
	Iron_inv: class extends self.ISpriteInstance {},
	NormTest: class extends self.ITextInstance {},
	junk: class extends self.ISpriteInstance {},
	junk2: class extends self.ISpriteInstance {},
	Lead: class extends self.ISpriteInstance {},
	Lead_count: class extends self.ITextInstance {},
	Lead_inv: class extends self.ISpriteInstance {},
	load32_: class extends self.ISpriteInstance {},
	mark: class extends self.ISpriteInstance {},
	mark2: class extends self.ISpriteInstance {},
	mask: class extends self.ISpriteInstance {},
	mask2: class extends self.ISpriteInstance {},
	Middle_frame: class extends self.ISpriteInstance {},
	money_bar: class extends self.ISpriteInstance {},
	Monster_Power: class extends self.ITextInstance {},
	Music: class extends self.ITextInstance {},
	Name: class extends self.ITextInstance {},
	Pickaxe_Power: class extends self.ITextInstance {},
	progress_bar_fill: class extends self.ISpriteInstance {},
	Progress_bar_frame: class extends self.ISpriteInstance {},
	progress_bar_milestones1: class extends self.ISpriteInstance {},
	Resource_frame: class extends self.ISpriteInstance {},
	result_window: class extends self.ISpriteInstance {},
	rocks_tunnel_: class extends self.ISpriteInstance {},
	Shadow: class extends self.ISpriteInstance {},
	Silver: class extends self.ISpriteInstance {},
	Silver_count: class extends self.ITextInstance {},
	Silver_inv: class extends self.ISpriteInstance {},
	Small_frame: class extends self.ISpriteInstance {},
	Sound: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	take_reward_button: class extends self.ISpriteInstance {},
	TextRandom: class extends self.ITextInstance {},
	version: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	tool: class extends self.ISpriteInstance {},
	tunnel1: class extends self.ISpriteInstance {},
	tunnel2: class extends self.ISpriteInstance {},
	hearth_txt: class extends self.ITextInstance {},
	health_sprite: class extends self.ISpriteInstance {},
	health_sprite2: class extends self.ISpriteInstance {},
	health_sprite3: class extends self.ISpriteInstance {},
	PickAxe_Range_txt: class extends self.ITextInstance {},
	mood_txt: class extends self.ITextInstance {},
	Happiness_sprite: class extends self.ISpriteInstance {},
	Happiness_Sprite2: class extends self.ISpriteInstance {},
	Happiness_Sprite3: class extends self.ISpriteInstance {},
	hunger_txt: class extends self.ITextInstance {},
	Hunger_Sprite: class extends self.ISpriteInstance {},
	Hunger_Sprite2: class extends self.ISpriteInstance {},
	Hunger_Sprite3: class extends self.ISpriteInstance {},
	purity_txt: class extends self.ITextInstance {},
	Purity_Sprite: class extends self.ISpriteInstance {},
	Purity_Sprite2: class extends self.ISpriteInstance {},
	Purity_Sprite3: class extends self.ISpriteInstance {},
	dontxt: class extends self.ITextInstance {},
	sleep_debug: class extends self.ITextInstance {},
	AnimType: class extends self.ITextInstance {},
	junktest: class extends self.ITextInstance {},
	obj_health_icon: class extends self.ISpriteInstance {},
	obj_mood_icon: class extends self.ISpriteInstance {},
	obj_hunger_icon: class extends self.ISpriteInstance {},
	obj_purity_icon: class extends self.ISpriteInstance {},
	LocalName: class extends self.ITextInstance {},
	Tg_ID: class extends self.ITextInstance {},
	api_debug: class extends self.ITextInstance {},
	RareTest: class extends self.ITextInstance {},
	LegendTest: class extends self.ITextInstance {},
	CurrentEventTxt: class extends self.ITextInstance {},
	tap_object_txt: class extends self.ITextInstance {},
	ProbabStatEventTxt: class extends self.ITextInstance {},
	Attack_boom: class extends self.ISpriteInstance {},
	Baff_effect: class extends self.ISpriteInstance {},
	Pickaxedisplay_txt: class extends self.ITextInstance {},
	progress_bar_milestones2: class extends self.ISpriteInstance {},
	progress_bar_milestones4: class extends self.ISpriteInstance {},
	progress_bar_milestones3: class extends self.ISpriteInstance {},
	aid_btn: class extends self.ISpriteInstance {},
	button_frame: class extends self.ISpriteInstance {},
	Down_panel: class extends self.ISpriteInstance {},
	energy_progress_bar: class extends self.ITiledBackgroundInstance {},
	settings_btn: class extends self.ISpriteInstance {},
	workshop_btn: class extends self.ISpriteInstance {},
	shower_btn: class extends self.ISpriteInstance {},
	sleep_btn: class extends self.ISpriteInstance {},
	mood_progress_bar_green: class extends self.ITiledBackgroundInstance {},
	stats_panel: class extends self.ISpriteInstance {},
	tool_btn: class extends self.ISpriteInstance {},
	purity_progress_bar_green: class extends self.ITiledBackgroundInstance {},
	health_progress_bar_green: class extends self.ITiledBackgroundInstance {},
	hunger_progress_green: class extends self.ITiledBackgroundInstance {},
	NoMoney_panel: class extends self.ISpriteInstance {},
	main_shadow: class extends self.ISpriteInstance {},
	money_count_txt: class extends self.ITextInstance {},
	music_box: class extends self.ISpriteInstance {},
	music_Check: class extends self.ISpriteInstance {},
	no_btn_lvlup: class extends self.ISpriteInstance {},
	no_btn_sleep: class extends self.ISpriteInstance {},
	no_btn_upgrade: class extends self.ISpriteInstance {},
	no_btn_workshop: class extends self.ISpriteInstance {},
	NoMoneyTxt: class extends self.ITextInstance {},
	options_panel: class extends self.ISpriteInstance {},
	Player_name_txt: class extends self.ITextInstance {},
	PlayerShadow: class extends self.ISpriteInstance {},
	purity_stat_txt: class extends self.ITextInstance {},
	revive_button: class extends self.ISpriteInstance {},
	shop_shadow: class extends self.ISpriteInstance {},
	shop_window: class extends self.ISpriteInstance {},
	sleep_panel: class extends self.ISpriteInstance {},
	SleepTxt: class extends self.ITextInstance {},
	Small_obj_1: class extends self.ISpriteInstance {},
	sound_box: class extends self.ISpriteInstance {},
	sound_Check: class extends self.ISpriteInstance {},
	Sound_txt: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Stat_count: class extends self.ISpriteInstance {},
	taken_money_txt: class extends self.ITextInstance {},
	Tap_obj: class extends self.ISpriteInstance {},
	upgrade_btn: class extends self.ISpriteInstance {},
	Upgrade_price_txt: class extends self.ITextInstance {},
	workshop_bags_buy_btn: class extends self.ISpriteInstance {},
	workshop_bags_buy_check: class extends self.ISpriteInstance {},
	workshop_bags_price_txt: class extends self.ITextInstance {},
	workshop_bags_txt: class extends self.ITextInstance {},
	workshop_buy_panel: class extends self.ISpriteInstance {},
	workshop_buy_txt: class extends self.ITextInstance {},
	workshop_deep_buy_btn: class extends self.ISpriteInstance {},
	workshop_deep_txt: class extends self.ITextInstance {},
	workshop_header_txt: class extends self.ITextInstance {},
	workshop_main_panel: class extends self.ISpriteInstance {},
	workshop_pickaxe_buy_check: class extends self.ISpriteInstance {},
	workshop_pickaxe_price_txt: class extends self.ITextInstance {},
	workshop_Pickaxe_skin_txt: class extends self.ITextInstance {},
	workshop_pickxe_buy_btn: class extends self.ISpriteInstance {},
	workshop_shadow: class extends self.ISpriteInstance {},
	workshop_upgrade_price_txt: class extends self.ITextInstance {},
	yes_btn_lvlup: class extends self.ISpriteInstance {},
	yes_btn_sleep: class extends self.ISpriteInstance {},
	yes_btn_buy: class extends self.ISpriteInstance {},
	yes_btn_workshop: class extends self.ISpriteInstance {},
	_1_item_1added_stat_txt: class extends self.ITextInstance {},
	_1_item_2added_stat_txt: class extends self.ITextInstance {},
	_1_item_price_txt: class extends self.ITextInstance {},
	_1_item_stat_bonus_icon: class extends self.ISpriteInstance {},
	_1_slot_item: class extends self.ISpriteInstance {},
	_1_slot_item_count: class extends self.ITextInstance {},
	slot_buy_btn: class extends self.ISpriteInstance {},
	_2_item_1added_stat_txt: class extends self.ITextInstance {},
	_2_item_2added_stat_txt: class extends self.ITextInstance {},
	_2_slot_item: class extends self.ISpriteInstance {},
	_2_slot_item_count: class extends self.ITextInstance {},
	_3_item_1added_stat_txt: class extends self.ITextInstance {},
	_3_item_2added_stat_txt: class extends self.ITextInstance {},
	_3_slot_item: class extends self.ISpriteInstance {},
	_3_slot_item_count: class extends self.ITextInstance {},
	_4_slot_item: class extends self.ISpriteInstance {},
	_4_slot_item_count: class extends self.ITextInstance {},
	_5_slot_item: class extends self.ISpriteInstance {},
	_5_slot_item_count: class extends self.ITextInstance {},
	_6_slot_item: class extends self.ISpriteInstance {},
	_6_slot_item_count: class extends self.ITextInstance {},
	added_stat_txt1: class extends self.ITextInstance {},
	added_stat_txt2: class extends self.ITextInstance {},
	close_workshop: class extends self.ISpriteInstance {},
	debug_energy_btn: class extends self.ISpriteInstance {},
	debug_energy_btn_2: class extends self.ISpriteInstance {},
	debug_health_btn: class extends self.ISpriteInstance {},
	debug_health_btn2: class extends self.ISpriteInstance {},
	dont: class extends self.ISpriteInstance {},
	energy_count_txt: class extends self.ITextInstance {},
	energy_icon: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	hapiness_stat_txt: class extends self.ITextInstance {},
	health_stat_txt: class extends self.ITextInstance {},
	hunger_stat_txt: class extends self.ITextInstance {},
	levelup_panel: class extends self.ISpriteInstance {},
	LvlupTxt: class extends self.ITextInstance {},
	_2_item_price_txt: class extends self.ITextInstance {},
	_3_item_price_txt: class extends self.ITextInstance {},
	mood_progress_bar_yellow: class extends self.ITiledBackgroundInstance {},
	mood_progress_bar_red: class extends self.ITiledBackgroundInstance {},
	purity_progress_yellow: class extends self.ITiledBackgroundInstance {},
	purity_progress_red: class extends self.ITiledBackgroundInstance {},
	health_progress_bar_yellow: class extends self.ITiledBackgroundInstance {},
	health_progress_red: class extends self.ITiledBackgroundInstance {},
	hunger_progress_yellow: class extends self.ITiledBackgroundInstance {},
	hunger_progress_red: class extends self.ITiledBackgroundInstance {},
	obj_health_icon_base: class extends self.ISpriteInstance {},
	obj_hunger_icon_base: class extends self.ISpriteInstance {},
	obj_mood_icon_base: class extends self.ISpriteInstance {},
	obj_purity_icon_base: class extends self.ISpriteInstance {},
	BlockScreen: class extends self.ISpriteInstance {},
	dino: class extends self.ISpriteInstance {},
	door_button: class extends self.ISpriteInstance {},
	doors: class extends self.ISpriteInstance {},
	DoorTxt: class extends self.ITextInstance {},
	upgrade_price_icon: class extends self.ISpriteInstance {},
	tutorail_shadow: class extends self.ISpriteInstance {},
	FoxNews: class extends self.IWorldInstance {},
	Cutscene_txt: class extends self.ITextInstance {},
	skip: class extends self.IButtonInstance {},
	TutorialHand: class extends self.ISpriteInstance {},
	TutorialPopup: class extends self.ISpriteInstance {},
	TutorialMask1: class extends self.ISpriteInstance {},
	TutorialMask2: class extends self.ISpriteInstance {},
	TutorialTxt: class extends self.ITextInstance {},
	skip2: class extends self.IButtonInstance {},
	debugTxt: class extends self.ITextInstance {},
	debugTxt2: class extends self.ITextInstance {},
	playBtn: class extends self.ISpriteInstance {},
	NewFox: class extends self.IHTMLElementInstance {},
	redbull: class extends self.ISpriteInstance {},
	Loading_animation: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	GameAnalytics: class extends self.IInstance {},
	HitExplosion1: class extends self.ISpriteInstance {},
	HitExplosion2: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	LoadingBg: class extends self.ISpriteInstance {},
	loading_txt: class extends self.ITextInstance {},
	Debug_Load_txt: class extends self.ITextInstance {},
	LevelTxt: class extends self.ITextInstance {},
	MultiplierPic: class extends self.ISpriteInstance {},
	Multiplyer_txt: class extends self.ITextInstance {},
	RecipeIcon: class extends self.ISpriteInstance {},
	MisiionFrame: class extends self.ISpriteInstance {},
	MissonIcon: class extends self.ISpriteInstance {},
	MissionObject: class extends self.ISpriteInstance {},
	MissionTxt: class extends self.ITextInstance {},
	tunnel: class extends self.ISpriteInstance {},
	rocks: class extends self.ISpriteInstance {},
	JunkFam: class extends self.ISpriteInstance {},
	Event_fam: class extends self.ITextInstance {},
	Digging: class extends self.ISpriteInstance {},
	Event_stats: class extends self.ISpriteInstance {},
	Stat_txt: class extends self.ITextInstance {},
	EventUI: class extends self.ISpriteInstance {},
	Inventory_window: class extends self.ISpriteInstance {},
	Inventory_count_text: class extends self.ITextInstance {},
	Main_UI_buttons: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.ISpriteInstance {},
	Shop_Window_Family: class extends self.ISpriteInstance {},
	Shop_window_txt_fam: class extends self.ITextInstance {},
	Slot_items: class extends self.ISpriteInstance {},
	Base_buttons: class extends self.ISpriteInstance {},
	Sleep_icons: class extends self.ISpriteInstance {},
	Sound_icons: class extends self.ISpriteInstance {},
	workshop_main_icons: class extends self.ISpriteInstance {},
	workshop_buy_btns: class extends self.ISpriteInstance {},
	workshop_txt: class extends self.ITextInstance {},
	TapIcons: class extends self.ISpriteInstance {},
	Price_txt: class extends self.ITextInstance {},
	Base_icons: class extends self.ISpriteInstance {},
	Additional_UI: class extends self.ISpriteInstance {},
	TutorialImages: class extends self.ISpriteInstance {}
}